spring.application.name=cfd

# variables de Railway por defecto (después de los :) apunta a local
spring.datasource.url=jdbc:mysql://${mysql.railway.internal:localhost}:${3306:3306}/${MYSQLDATABASE:railway}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC

# Usuario de la BD
spring.datasource.username=${root:root}

# Contraseña
spring.datasource.password=${AWRywuwQbcCcFnRxfJboHyjRZtBQGqzl:}


#spring.datasource.url=jdbc:mysql://localhost:3306/cfd_servicios?serverTimezone=UTC&useSSL=false
#spring.datasource.username=root
#spring.datasource.password=
# Configuración de JPA/hibernate
spring.jpa.hibernate.ddl-auto=update 
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# Configuración de logs 



